# Generated by Django 5.1.2 on 2024-10-20 13:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("yandex", "Yandex"),
                            ("mailru", "Mail.ru"),
                            ("gmail", "Gmail"),
                        ],
                        default="gmail",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Account",
                "verbose_name_plural": "Email Accounts",
                "db_table": "email_account",
            },
        ),
        migrations.CreateModel(
            name="EmailMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=255)),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("body", models.TextField(blank=True, null=True)),
                (
                    "from_address",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "email_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="mail_app.emailaccount",
                    ),
                ),
            ],
            options={
                "db_table": "email_message",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="attachments/")),
                ("filename", models.CharField(max_length=255)),
                (
                    "email_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="mail_app.emailmessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attachment",
                "verbose_name_plural": "Attachments",
                "db_table": "attachments",
            },
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["email_account", "uid"], name="email_messa_email_a_76d939_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["received_at"], name="email_messa_receive_733b11_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="emailmessage",
            unique_together={("email_account", "uid")},
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["email_message"], name="attachments_email_m_2bb366_idx"
            ),
        ),
    ]
