# Generated by Django 5.1.2 on 2024-10-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailaccount",
            name="highest_uid",
            field=models.BigIntegerField(default=0),
        ),
    ]
