# Generated by Django 5.1.2 on 2024-10-21 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail_app", "0002_emailaccount_highest_uid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailaccount",
            name="highest_uid",
        ),
    ]
